### PR TITLE
Add introduction

### PR DESCRIPTION
**Pull request by robinwhittleton**
Found I had time tonight after all :)

### CODE REVIEW

**Comment by acabal** [comment]
I see it's titled Introduction, but the filename and semantics are Preface. Which is it?

**Comment by robinwhittleton** [comment]
I typically leave the source title the same (in this case Inteoduction) but match the semantics do the [Z39.98 spec’s document divisions](https://daisy.org/activities/standards/daisy/z39-98-2012/z39-98-2012-structural-semantics-vocabulary/#h_document-sections). In this case `preface` seemed most appropriate but I’m happy to change.

**Comment by acabal** [comment]
OK got it. In that case let's just put a note in production-notes so that we know what decision we made, if someone goes back and gets confused later on.

**Comment by robinwhittleton** [comment]
Added a note, thanks.

**Comment by acabal** [comment]
Excellent, thanks!

**Pull request merged**
